import { chromium } from '/Users/thesimakov/.npm/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:760,height:820}, deviceScaleFactor:2 });
await ctx.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
const p = await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.addInitScript(()=>{ try{ const r=localStorage.getItem('widget-settings'); if(r){const m=JSON.parse(r); delete m['cb-preview']; localStorage.setItem('widget-settings',JSON.stringify(m));} }catch{} });
await p.goto('http://localhost:5173/preview/callback.html',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(3000);
await p.getByRole('button',{name:'Просмотр'}).click();
await p.waitForTimeout(700);
const tel = p.locator('input[type=tel]').last();
await tel.click(); await tel.type('9991234567',{delay:15});
await p.waitForTimeout(200);
await p.getByRole('button',{name:'Жду звонка'}).last().click();
await p.waitForTimeout(900);
console.log('ERR:', errs.slice(0,5).join(' | ')||'none');
await p.screenshot({ path:'w-call3.png' });
await b.close(); console.log('ok');
