import { chromium } from '/Users/thesimakov/.npm/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1320,height:900}, deviceScaleFactor:2 });
await ctx.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
const p = await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.addInitScript(()=>{ try{ const r=localStorage.getItem('widget-settings'); if(r){const m=JSON.parse(r); delete m['cb-preview']; localStorage.setItem('widget-settings',JSON.stringify(m));} }catch{} });
await p.goto('http://localhost:5173/preview/callback.html',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(3000);
// panel form is the visible "Форма" tab; fill phone, choose time, готово
const tel = p.locator('input[type=tel]').first(); await tel.click({force:true}); await tel.type('9991234567',{delay:8});
await p.getByText('Выбрать время для звонка').first().click({force:true});
await p.waitForTimeout(300);
const dt = p.locator('input[type="datetime-local"]').first(); await dt.fill('2026-02-12T12:00');
await p.getByText('Готово').first().click({force:true});
await p.waitForTimeout(500);
console.log('ERR:', errs.slice(0,5).join(' | ')||'none');
console.log('confirm:', await p.getByText('До связи').count());
await p.screenshot({ path:'confirm.png', clip:{x:868,y:80,width:452,height:560} });
await b.close(); console.log('ok');
