import { chromium } from '/Users/thesimakov/.npm/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1000,height:840}, deviceScaleFactor:2 });
await ctx.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
const p = await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push('PE: '+e.message)); p.on('console',m=>{if(m.type()==='error'&&!/ERR_FAILED|Zod schema|404|Failed to load resource/.test(m.text()))errs.push(m.text());});
await p.addInitScript(()=>{ try{ const r=localStorage.getItem('widget-settings'); if(r){const m=JSON.parse(r); delete m['cb-preview']; localStorage.setItem('widget-settings',JSON.stringify(m));} }catch{} });
await p.goto('http://localhost:5173/preview/callback.html',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(3000);
await p.getByRole('button',{name:'Просмотр'}).click();
await p.waitForTimeout(400);
await p.locator('button[aria-label="Обратный звонок"]').click();
await p.waitForTimeout(600);
console.log('ERR:', errs.slice(0,8).join(' | ')||'none');
console.log('link count:', await p.getByText('Выбрать время для звонка').count());
await p.getByText('Выбрать время для звонка').first().click();
await p.waitForTimeout(400);
const tel = p.locator('input[type=tel]').last(); await tel.click(); await tel.type('9991234567',{delay:10});
const dt = p.locator('input[type="datetime-local"]').last(); await dt.fill('2026-02-12T12:00');
await p.screenshot({ path:'def-picker.png' });
await p.getByRole('button',{name:'Готово'}).first().click();
await p.waitForTimeout(500);
await p.screenshot({ path:'def-confirm.png' });
await b.close(); console.log('ok');
