import { chromium } from '/Users/thesimakov/.npm/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1000,height:860}, deviceScaleFactor:2 });
await ctx.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
const p = await ctx.newPage();
await p.addInitScript(()=>{ try{ const r=localStorage.getItem('widget-settings'); if(r){const m=JSON.parse(r); delete m['cb-preview']; localStorage.setItem('widget-settings',JSON.stringify(m));} }catch{} });
await p.goto('http://localhost:5173/preview/callback.html',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(2800);
await p.getByRole('button',{name:'Просмотр'}).click();
await p.waitForSelector('button[aria-label="Обратный звонок"]',{timeout:8000});
await p.locator('button[aria-label="Обратный звонок"]').click();
await p.waitForSelector('text=Выбрать время для звонка',{timeout:8000});
const tel = p.locator('input[type=tel]').last(); await tel.click(); await tel.type('9991234567',{delay:10});
await p.getByText('Выбрать время для звонка').first().click();
await p.waitForTimeout(400);
const dt = p.locator('input[type="datetime-local"]').last(); await dt.fill('2026-02-12T12:00');
await p.screenshot({ path:'def-picker.png' });
await p.getByRole('button',{name:'Готово'}).first().click();
await p.waitForTimeout(500);
await p.screenshot({ path:'def-confirm.png' });
await b.close(); console.log('ok');
