import { chromium } from '/Users/thesimakov/.npm/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1000,height:860}, deviceScaleFactor:2 });
await ctx.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
const p = await ctx.newPage();
await p.addInitScript(()=>{ try{ const r=localStorage.getItem('widget-settings'); if(r){const m=JSON.parse(r); delete m['cb-preview']; localStorage.setItem('widget-settings',JSON.stringify(m));} }catch{} });
await p.goto('http://localhost:5173/preview/callback.html',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(2800);
await p.getByRole('button',{name:'Просмотр'}).click({force:true});
await p.waitForTimeout(700);
await p.locator('button[aria-label="Обратный звонок"]').click({force:true});
await p.waitForTimeout(800);
// плавающая форма = последняя карточка
await p.getByText('Выбрать время для звонка').last().click({force:true});
await p.waitForTimeout(500);
console.log('datetime:', await p.locator('input[type="datetime-local"]').count(), 'now:', await p.getByText('Позвонить сейчас').count());
await p.screenshot({ path:'def-picker.png' });
const dt = p.locator('input[type="datetime-local"]').last(); await dt.fill('2026-02-12T12:00');
await p.getByText('Готово').last().click({force:true});
await p.waitForTimeout(500);
console.log('confirm:', await p.getByText('Ожидайте звонка').count());
await p.screenshot({ path:'def-confirm.png' });
await b.close(); console.log('ok');
