import { chromium } from '/Users/thesimakov/.npm/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:900,height:820}, deviceScaleFactor:2 });
await ctx.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
const p = await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.addInitScript(()=>{ try{ const r=localStorage.getItem('widget-settings'); if(r){const m=JSON.parse(r); delete m['cb-preview']; localStorage.setItem('widget-settings',JSON.stringify(m));} }catch{} });
await p.goto('http://localhost:5173/preview/callback.html',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(2800);
await p.getByRole('button',{name:'Просмотр'}).click({force:true});
await p.waitForTimeout(700);
await p.locator('button[aria-label="Обратный звонок"]').click({force:true});
await p.waitForTimeout(700);
const tel = p.locator('input[type=tel]').last(); await tel.click({force:true}); await tel.type('9991234567',{delay:10});
await p.getByRole('button',{name:'Жду звонка'}).last().click({force:true});
await p.waitForTimeout(1600);
console.log('ERR:', errs.slice(0,5).join(' | ')||'none');
await p.screenshot({ path:'t-call.png' });
await b.close(); console.log('ok');
