/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IncludedPlanOptionDto } from './included-plan-option-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentPlanOptionDto } from './payment-plan-option-dto';

/**
 * 
 * @export
 * @interface PaymentPlanDto
 */
export interface PaymentPlanDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanDto
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentPlanDto
     */
    'enabled': boolean;
    /**
     * 
     * @type {number}
     * @memberof PaymentPlanDto
     */
    'numberOfProjects': number;
    /**
     * 
     * @type {number}
     * @memberof PaymentPlanDto
     */
    'numberOfWidgets': number;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanDto
     */
    'monthlyPrice': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanDto
     */
    'quarterlyPrice': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanDto
     */
    'yearlyPrice': string;
    /**
     * 
     * @type {Array<PaymentPlanOptionDto>}
     * @memberof PaymentPlanDto
     */
    'paymentPlanOptions': Array<PaymentPlanOptionDto>;
    /**
     * 
     * @type {Array<IncludedPlanOptionDto>}
     * @memberof PaymentPlanDto
     */
    'includedPlanOptions': Array<IncludedPlanOptionDto>;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanDto
     */
    'updatedAt': string;
}

