/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentPlanEntiity
 */
export interface PaymentPlanEntiity {
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanEntiity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanEntiity
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentPlanEntiity
     */
    'enabled': boolean;
    /**
     * 
     * @type {number}
     * @memberof PaymentPlanEntiity
     */
    'numberOfProjects': number;
    /**
     * 
     * @type {number}
     * @memberof PaymentPlanEntiity
     */
    'numberOfWidgets': number;
    /**
     * 
     * @type {number}
     * @memberof PaymentPlanEntiity
     */
    'monthlyPrice': number;
    /**
     * 
     * @type {number}
     * @memberof PaymentPlanEntiity
     */
    'quarterlyPrice': number;
    /**
     * 
     * @type {number}
     * @memberof PaymentPlanEntiity
     */
    'yearlyPrice': number;
    /**
     * 
     * @type {number}
     * @memberof PaymentPlanEntiity
     */
    'brandingPrice': number;
    /**
     * 
     * @type {object}
     * @memberof PaymentPlanEntiity
     */
    'options': object;
}

