/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentPlanOptionDto
 */
export interface PaymentPlanOptionDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanOptionDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanOptionDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanOptionDto
     */
    'type': string;
    /**
     * 
     * @type {number}
     * @memberof PaymentPlanOptionDto
     */
    'price': number;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentPlanOptionDto
     */
    'enabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentPlanOptionDto
     */
    'isBilledAnnually': boolean;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanOptionDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentPlanOptionDto
     */
    'updatedAt': string;
}

