/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentPlanDto } from './payment-plan-dto';

/**
 * 
 * @export
 * @interface PaymentInfoResponse
 */
export interface PaymentInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof PaymentInfoResponse
     */
    'balance': number;
    /**
     * 
     * @type {Array<PaymentPlanDto>}
     * @memberof PaymentInfoResponse
     */
    'paymentPlan'?: Array<PaymentPlanDto>;
}

