/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentInfoPaymentOptionDto
 */
export interface PaymentInfoPaymentOptionDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentInfoPaymentOptionDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentInfoPaymentOptionDto
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentInfoPaymentOptionDto
     */
    'name': string;
}

