/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentInfoPaymentOptionDto } from './payment-info-payment-option-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentPlanDto } from './payment-plan-dto';

/**
 * 
 * @export
 * @interface PaymentInfoDto
 */
export interface PaymentInfoDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentInfoDto
     */
    'balance': string;
    /**
     * 
     * @type {PaymentPlanDto}
     * @memberof PaymentInfoDto
     */
    'paymentPlan'?: PaymentPlanDto;
    /**
     * 
     * @type {string}
     * @memberof PaymentInfoDto
     */
    'paymentPlanStartDate': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentInfoDto
     */
    'paymentPlanEndDate': string;
    /**
     * 
     * @type {Array<PaymentInfoPaymentOptionDto>}
     * @memberof PaymentInfoDto
     */
    'purchasedPaymentPlanOptions': Array<PaymentInfoPaymentOptionDto>;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentInfoDto
     */
    'usedTrialPeriod': boolean;
}

