/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserPaymentInfoDto
 */
export interface UpdateUserPaymentInfoDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPaymentInfoDto
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPaymentInfoDto
     */
    'paymentPlanId': string;
    /**
     * 
     * @type {object}
     * @memberof UpdateUserPaymentInfoDto
     */
    'optionsInCart': object;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPaymentInfoDto
     */
    'billingPeriod': string;
}

