/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateYooMoneyPaymentDto } from '../models';
// @ts-ignore
import type { PaymentInfoDto } from '../models';
// @ts-ignore
import type { PaymentPlanDto } from '../models';
// @ts-ignore
import type { PromoDto } from '../models';
// @ts-ignore
import type { UpdateUserPaymentInfoDto } from '../models';
/**
 * PaymentApi - axios parameter creator
 * @export
 */
export const PaymentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerCheckForPaymentUpdates: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('paymentControllerCheckForPaymentUpdates', 'id', id)
            const localVarPath = `/api/payment/check/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateYooMoneyPaymentDto} createYooMoneyPaymentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerCreateYooMoneyPayment: async (createYooMoneyPaymentDto: CreateYooMoneyPaymentDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createYooMoneyPaymentDto' is not null or undefined
            assertParamExists('paymentControllerCreateYooMoneyPayment', 'createYooMoneyPaymentDto', createYooMoneyPaymentDto)
            const localVarPath = `/api/payment/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createYooMoneyPaymentDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerDeletePayment: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('paymentControllerDeletePayment', 'id', id)
            const localVarPath = `/api/payment/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerGetPaymentPlan: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('paymentControllerGetPaymentPlan', 'id', id)
            const localVarPath = `/api/payment/plans/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} promo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerGetPromo: async (promo: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'promo' is not null or undefined
            assertParamExists('paymentControllerGetPromo', 'promo', promo)
            const localVarPath = `/api/payment/promo/{promo}`
                .replace(`{${"promo"}}`, encodeURIComponent(String(promo)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerGetTodaysPendingPayments: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payment/pending`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerGetUserPaymentInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payment/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerSelectAllEnabledPaymentPlans: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/payment/plans`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateUserPaymentInfoDto} updateUserPaymentInfoDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerUpdateUserPaymentInfo: async (updateUserPaymentInfoDto: UpdateUserPaymentInfoDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateUserPaymentInfoDto' is not null or undefined
            assertParamExists('paymentControllerUpdateUserPaymentInfo', 'updateUserPaymentInfoDto', updateUserPaymentInfoDto)
            const localVarPath = `/api/payment/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserPaymentInfoDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentApi - functional programming interface
 * @export
 */
export const PaymentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerCheckForPaymentUpdates(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerCheckForPaymentUpdates(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.paymentControllerCheckForPaymentUpdates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateYooMoneyPaymentDto} createYooMoneyPaymentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerCreateYooMoneyPayment(createYooMoneyPaymentDto: CreateYooMoneyPaymentDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerCreateYooMoneyPayment(createYooMoneyPaymentDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.paymentControllerCreateYooMoneyPayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerDeletePayment(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerDeletePayment(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.paymentControllerDeletePayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerGetPaymentPlan(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentPlanDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerGetPaymentPlan(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.paymentControllerGetPaymentPlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} promo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerGetPromo(promo: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PromoDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerGetPromo(promo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.paymentControllerGetPromo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerGetTodaysPendingPayments(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerGetTodaysPendingPayments(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.paymentControllerGetTodaysPendingPayments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerGetUserPaymentInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentInfoDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerGetUserPaymentInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.paymentControllerGetUserPaymentInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerSelectAllEnabledPaymentPlans(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentPlanDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerSelectAllEnabledPaymentPlans(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.paymentControllerSelectAllEnabledPaymentPlans']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateUserPaymentInfoDto} updateUserPaymentInfoDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentControllerUpdateUserPaymentInfo(updateUserPaymentInfoDto: UpdateUserPaymentInfoDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerUpdateUserPaymentInfo(updateUserPaymentInfoDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.paymentControllerUpdateUserPaymentInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaymentApi - factory interface
 * @export
 */
export const PaymentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentApiFp(configuration)
    return {
        /**
         * 
         * @param {PaymentApiPaymentControllerCheckForPaymentUpdatesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerCheckForPaymentUpdates(requestParameters: PaymentApiPaymentControllerCheckForPaymentUpdatesRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.paymentControllerCheckForPaymentUpdates(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PaymentApiPaymentControllerCreateYooMoneyPaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerCreateYooMoneyPayment(requestParameters: PaymentApiPaymentControllerCreateYooMoneyPaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.paymentControllerCreateYooMoneyPayment(requestParameters.createYooMoneyPaymentDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PaymentApiPaymentControllerDeletePaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerDeletePayment(requestParameters: PaymentApiPaymentControllerDeletePaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.paymentControllerDeletePayment(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PaymentApiPaymentControllerGetPaymentPlanRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerGetPaymentPlan(requestParameters: PaymentApiPaymentControllerGetPaymentPlanRequest, options?: RawAxiosRequestConfig): AxiosPromise<PaymentPlanDto> {
            return localVarFp.paymentControllerGetPaymentPlan(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PaymentApiPaymentControllerGetPromoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerGetPromo(requestParameters: PaymentApiPaymentControllerGetPromoRequest, options?: RawAxiosRequestConfig): AxiosPromise<PromoDto> {
            return localVarFp.paymentControllerGetPromo(requestParameters.promo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerGetTodaysPendingPayments(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.paymentControllerGetTodaysPendingPayments(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerGetUserPaymentInfo(options?: RawAxiosRequestConfig): AxiosPromise<PaymentInfoDto> {
            return localVarFp.paymentControllerGetUserPaymentInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerSelectAllEnabledPaymentPlans(options?: RawAxiosRequestConfig): AxiosPromise<PaymentPlanDto> {
            return localVarFp.paymentControllerSelectAllEnabledPaymentPlans(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PaymentApiPaymentControllerUpdateUserPaymentInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentControllerUpdateUserPaymentInfo(requestParameters: PaymentApiPaymentControllerUpdateUserPaymentInfoRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.paymentControllerUpdateUserPaymentInfo(requestParameters.updateUserPaymentInfoDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for paymentControllerCheckForPaymentUpdates operation in PaymentApi.
 * @export
 * @interface PaymentApiPaymentControllerCheckForPaymentUpdatesRequest
 */
export interface PaymentApiPaymentControllerCheckForPaymentUpdatesRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentApiPaymentControllerCheckForPaymentUpdates
     */
    readonly id: string
}

/**
 * Request parameters for paymentControllerCreateYooMoneyPayment operation in PaymentApi.
 * @export
 * @interface PaymentApiPaymentControllerCreateYooMoneyPaymentRequest
 */
export interface PaymentApiPaymentControllerCreateYooMoneyPaymentRequest {
    /**
     * 
     * @type {CreateYooMoneyPaymentDto}
     * @memberof PaymentApiPaymentControllerCreateYooMoneyPayment
     */
    readonly createYooMoneyPaymentDto: CreateYooMoneyPaymentDto
}

/**
 * Request parameters for paymentControllerDeletePayment operation in PaymentApi.
 * @export
 * @interface PaymentApiPaymentControllerDeletePaymentRequest
 */
export interface PaymentApiPaymentControllerDeletePaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentApiPaymentControllerDeletePayment
     */
    readonly id: string
}

/**
 * Request parameters for paymentControllerGetPaymentPlan operation in PaymentApi.
 * @export
 * @interface PaymentApiPaymentControllerGetPaymentPlanRequest
 */
export interface PaymentApiPaymentControllerGetPaymentPlanRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentApiPaymentControllerGetPaymentPlan
     */
    readonly id: string
}

/**
 * Request parameters for paymentControllerGetPromo operation in PaymentApi.
 * @export
 * @interface PaymentApiPaymentControllerGetPromoRequest
 */
export interface PaymentApiPaymentControllerGetPromoRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentApiPaymentControllerGetPromo
     */
    readonly promo: string
}

/**
 * Request parameters for paymentControllerUpdateUserPaymentInfo operation in PaymentApi.
 * @export
 * @interface PaymentApiPaymentControllerUpdateUserPaymentInfoRequest
 */
export interface PaymentApiPaymentControllerUpdateUserPaymentInfoRequest {
    /**
     * 
     * @type {UpdateUserPaymentInfoDto}
     * @memberof PaymentApiPaymentControllerUpdateUserPaymentInfo
     */
    readonly updateUserPaymentInfoDto: UpdateUserPaymentInfoDto
}

/**
 * PaymentApi - object-oriented interface
 * @export
 * @class PaymentApi
 * @extends {BaseAPI}
 */
export class PaymentApi extends BaseAPI {
    /**
     * 
     * @param {PaymentApiPaymentControllerCheckForPaymentUpdatesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerCheckForPaymentUpdates(requestParameters: PaymentApiPaymentControllerCheckForPaymentUpdatesRequest, options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).paymentControllerCheckForPaymentUpdates(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PaymentApiPaymentControllerCreateYooMoneyPaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerCreateYooMoneyPayment(requestParameters: PaymentApiPaymentControllerCreateYooMoneyPaymentRequest, options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).paymentControllerCreateYooMoneyPayment(requestParameters.createYooMoneyPaymentDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PaymentApiPaymentControllerDeletePaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerDeletePayment(requestParameters: PaymentApiPaymentControllerDeletePaymentRequest, options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).paymentControllerDeletePayment(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PaymentApiPaymentControllerGetPaymentPlanRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerGetPaymentPlan(requestParameters: PaymentApiPaymentControllerGetPaymentPlanRequest, options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).paymentControllerGetPaymentPlan(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PaymentApiPaymentControllerGetPromoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerGetPromo(requestParameters: PaymentApiPaymentControllerGetPromoRequest, options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).paymentControllerGetPromo(requestParameters.promo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerGetTodaysPendingPayments(options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).paymentControllerGetTodaysPendingPayments(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerGetUserPaymentInfo(options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).paymentControllerGetUserPaymentInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerSelectAllEnabledPaymentPlans(options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).paymentControllerSelectAllEnabledPaymentPlans(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PaymentApiPaymentControllerUpdateUserPaymentInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApi
     */
    public paymentControllerUpdateUserPaymentInfo(requestParameters: PaymentApiPaymentControllerUpdateUserPaymentInfoRequest, options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).paymentControllerUpdateUserPaymentInfo(requestParameters.updateUserPaymentInfoDto, options).then((request) => request(this.axios, this.basePath));
    }
}

