/* tslint:disable */
/* eslint-disable */
/**
 * Lemnity API
 * The Lemnity API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * PublicProjectsApi - axios parameter creator
 * @export
 */
export const PublicProjectsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicProjectControllerFindProjectWidgetIds: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('publicProjectControllerFindProjectWidgetIds', 'id', id)
            const localVarPath = `/api/public/projects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PublicProjectsApi - functional programming interface
 * @export
 */
export const PublicProjectsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PublicProjectsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async publicProjectControllerFindProjectWidgetIds(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.publicProjectControllerFindProjectWidgetIds(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicProjectsApi.publicProjectControllerFindProjectWidgetIds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PublicProjectsApi - factory interface
 * @export
 */
export const PublicProjectsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PublicProjectsApiFp(configuration)
    return {
        /**
         * 
         * @param {PublicProjectsApiPublicProjectControllerFindProjectWidgetIdsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicProjectControllerFindProjectWidgetIds(requestParameters: PublicProjectsApiPublicProjectControllerFindProjectWidgetIdsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.publicProjectControllerFindProjectWidgetIds(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for publicProjectControllerFindProjectWidgetIds operation in PublicProjectsApi.
 * @export
 * @interface PublicProjectsApiPublicProjectControllerFindProjectWidgetIdsRequest
 */
export interface PublicProjectsApiPublicProjectControllerFindProjectWidgetIdsRequest {
    /**
     * 
     * @type {string}
     * @memberof PublicProjectsApiPublicProjectControllerFindProjectWidgetIds
     */
    readonly id: string
}

/**
 * PublicProjectsApi - object-oriented interface
 * @export
 * @class PublicProjectsApi
 * @extends {BaseAPI}
 */
export class PublicProjectsApi extends BaseAPI {
    /**
     * 
     * @param {PublicProjectsApiPublicProjectControllerFindProjectWidgetIdsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicProjectsApi
     */
    public publicProjectControllerFindProjectWidgetIds(requestParameters: PublicProjectsApiPublicProjectControllerFindProjectWidgetIdsRequest, options?: RawAxiosRequestConfig) {
        return PublicProjectsApiFp(this.configuration).publicProjectControllerFindProjectWidgetIds(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

